### ISSUE TITLE
Other wiktionaries

### ISSUE THREAD

**Issue by FranklinYu** [losnappas/Context-menu-dictionary#14]
Is it planned to support other Wiktionaries besides English Wiktionary?

**Comment by losnappas** [comment]
Unfortunately the api that this addon uses is only available for the English Wiktionary.
And the API development (by Wiktionary/Wikimedia) has pretty much stalled, as far as I know. So I wouldn't hold my hopes up right now.

https://en.wiktionary.org/api/rest_v1/
under wiki page of the /page/definition/{term} section

>Status (as of 2016)
The feature is an experimental MVP and enabled only for articles on English Wikipedia. Due to the time cost of expanding the feature to other languages (see Obstacles), further work on the feature is pending based on user engagement.

**Comment by FranklinYu** [comment]
All right… In the “Obstacles” section:

> Wiktionary content is unstructured, and presenting a concise set of definitions requires parsing them from the page HTML.

Then how about using the [HTML API](https://zh.wiktionary.org/api/rest_v1/#!/Page_content/get_page_html_title)? That one is available in every language.

**Comment by losnappas** [comment]
For non-English languages, It's better than I thought it'd be. However, that api gives off pretty odd looking documents sometimes. Still, it might be better than nothing. Using it is very simple as it gives the full page, so that's a plus.

https://zh.wiktionary.org/api/rest_v1/page/html/moi
https://pl.wiktionary.org/api/rest_v1/page/html/moi

I'd just display them as they come, and inject some CSS on top to get the popup colors. But there's no way I'd be doing any sort of parsing there. That's just an impossible task, seeing that every wiktionary is so different.

I might give it a shot in the near future (next week probably) and see how it turns out.

**Comment by FranklinYu** [comment]
Totally agree. Trying parsing it will break here and there (there is no consensus about page structure in Chinese Wiktionary, for instance), so injecting CSS is the way to go. If there is an issue, it's probably the Wiktionary page itself that broke.

**Comment by losnappas** [comment]
Chose to instead open the associated full Wiktionary page. Firefox has some slight issues displaying pages in the popup (the bug tracker has like a gorillion issues about this), but it's pretty ok.

**Comment by FranklinYu** [comment]
https://github.com/losnappas/Context-menu-Wiktionary/blob/95c0c6b20217e52159c8037b2ec6ce7129fb0492/background.js#L14

I prefer `/api/rest_v1/page/html/` over `/wiki/`. The sidebar, header and footer in a full page may look bloated.

**Comment by losnappas** [comment]
I didn't realize how easy it is to do that too. But injecting the CSS is tricky. There's not really any good way of knowing when the popup has opened that I can think of.
I'm gonna wait and see for the CSS. I'll make an option for using the api/rest_v1.../html api.

for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1419713

**Comment by losnappas** [comment]
#17 Clicking links is "broken".. Didn't even test before uploading.

**Comment by FranklinYu** [comment]
One work-around is to wrap the pop-up in an `<iframe>`, but I’m not sure whether that worth the hassle…

**Comment by losnappas** [comment]
Yeah, that is a possibility. But quite the hassle as you mentioned. However, right now the links are pretty uhh.. rough. I'll see what the discussion in the bug report yields before committing to doing anything.

**Comment by losnappas** [comment]
The links seem to have fixed themselves. I assume Mozilla is behind this.
