### ISSUE TITLE
Simplified Chinese

### ISSUE THREAD

**Issue by GrimPixel** [losnappas/Context-menu-dictionary#19]
When I search for it with Simplified Chinese, it shows an error, not showing me the link the link to its Traditional counterpart. The page of that Traditional one exists.

**Comment by losnappas** [comment]
Are you using the compact formatting or not? Can you give me the Wiktionary url you are using.

**Comment by GrimPixel** [comment]
I am sorry for not be replying for so long.

For example, 欢迎 and 歡迎
https://en.wiktionary.org/wiki/%E6%AC%A2%E8%BF%8E
https://en.wiktionary.org/wiki/%E6%AD%A1%E8%BF%8E

**Comment by losnappas** [comment]
Hey, I just looked into this. I cannot do anything about the result since it's provided by the wiktionary API [here](https://en.wiktionary.org/api/rest_v1/page/definition/%E6%AC%A2%E8%BF%8E). However, if you specify "en.wiktionary.org" in the 'wiktionary language' box in preferences, then you will get results from the different API which does give you a redirection link to the term '歡迎'. You will lose the cute display style and fall back to the more traditional Wiktionary look, though.
