### ISSUE TITLE
Doesn't allow proper nouns to be looked up

### ISSUE THREAD

**Issue by Aelius51** [losnappas/Context-menu-dictionary#20]
For example, **Los Angeles** turns up no results, despite having a Wiktionary entry.

Even proper nouns spelled lowercase that Wiktionary [redirects](https://en.wiktionary.org/wiki/obama) to the upper case page - e.g., **obama** - don't work.

However, acronyms with ALL capital letters - e.g., **FBI** - can be looked up, probably as a result of version 2.0 which fixed #1.

**Comment by losnappas** [comment]
Yep, I gotta find a way to properly titlecase. There's a library https://github.com/wikimedia/mediawiki-title but I haven't yet gotten around to trying it. I'm hoping it'll work because it's really annoying the way it is right now.
tag: #15

edit: Just took another look at the lib, and I'm not too confidnet it'll be any good for this. I can think of one workaround, though. Will have to see once I have time.

**Comment by losnappas** [comment]
I just added a feature which offers alternate spellings for words if they 404. Right now, it offers UPPERCASE and Title Cased Versions.

Also, the project moved to gitlab: [https://gitlab.com/losnappas/Context-menu-Wiktionary](https://gitlab.com/losnappas/Context-menu-Wiktionary). But I won't hate on anyone for posting issues here if they so choose.

If you have ideas/needs for other spellings then I'd gladly hear them. Otherwise, I think this issue is settled.
